chore: Update Dockerfile and docker-image.yml for bot deployment and use secrets for Docker password

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,7 +16,17 @@ jobs:
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
-        username: ${{ github.actor }}
+        username: thuypq123
         password: ${{ secrets.DOCKER_PASSWORD }}
-    - name: Push the Docker image
-      run: docker push thuypq123/mg_bot:v1.0.0
+        ecr: auto
+        logout: true
+    - name: Check Docker login status
+      run: |
+        echo "Logging into ghcr.io..."
+        if ! docker login ghcr.io -u thuypq123 -p ${{ secrets.DOCKER_PASSWORD }}; then
+          echo "Error: Error response from daemon: Get \"https://ghcr.io/v2/\": denied: denied"
+          exit 1
+        fi
+        echo "Logged into ghcr.io"
+    - name: Pull the Docker image
+      run: docker pull thuypq123/mg_bot:v1.0.0
